---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appname }}
    tag: {{ .Values.imageTag }}
  name: {{ .Values.appname }}-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      tag: {{ .Values.imageTag }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        tag: {{ .Values.imageTag }}
    spec:
      containers:
      - image: {{ .Values.imageName }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Values.appname }}-{{ .Values.namespace }}
...
