apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appname }}
    tag: {{ .Values.imageTag }}
  name: {{ .Values.appname }}-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.serviceTargetPort }}
  selector:
    app: {{ .Values.appname }}
    tag: {{ .Values.imageTag }}
  type: {{ .Values.serviceType }}
