apiVersion: v1
kind: Service
metadata:
  name: python-helloworld-svc
  labels:
    run: python-helloworld
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
  selector:
    run: python-helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-helloworld
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      # lesson learned if you remove the version here it will attempt to pull
      # the 'latest' tag. 'latest' will only exist if you actually created or
      # updated the tag with an image. Much safer to specify a specific version.
      - image: rbriley/python-helloworld:1.0.3
        imagePullPolicy: IfNotPresent
        name: python-helloworld
        resources:
          requests:
            cpu: 50m
            memory: 256Mi

        ports:
          - name: helloworld-port
            containerPort: 5000
            hostPort: 5000

        readinessProbe:
          tcpSocket:
            port: helloworld-port
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: helloworld-port
          initialDelaySeconds: 10
          periodSeconds: 15