apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-helloworld
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      # lesson learned if you remove the version here it will attempt to pull
      # the 'latest' tag. 'latest' will only exist if you actually created or
      # updated the tag with an image. Much safer to specify a specific version.
      - image: rbriley/python-helloworld:1.0.3
        imagePullPolicy: IfNotPresent
        name: python-helloworld
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 15