---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-helloworld
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      # lesson learned if you remove the version here it will attempt to pull
      # the 'latest' tag. 'latest' will only exist if you actually created or
      # updated the tag with an image. Much safer to specify a specific version.
      - name: python-helloworld
        image: rbriley/python-helloworld:1.0.3
        imagePullPolicy: IfNotPresent
        ports:
          - name: helloworld-port
            containerPort: 5000
            protocol: TCP

        resources:
          requests:
            cpu: 50m
            memory: 256Mi

        readinessProbe:
          tcpSocket:
            port: helloworld-port
          initialDelaySeconds: 1
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /status
            port: helloworld-port
          initialDelaySeconds: 5
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: python-helloworld-svc
  namespace: default
  labels:
    app: python-helloworld
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    targetPort: 5000
    protocol: TCP
  selector:
    app: python-helloworld
...
